name       : lua
version    : 5.3.4
release    : 3
source     :
    - https://www.lua.org/ftp/lua-5.3.4.tar.gz : f681aa518233bc407e23acf0f5887c884f17436f000d453b2491a9f11a52400c
license    : MIT
component  : programming
summary    : Lightweight programming language
description: |
    Lua is a powerful light-weight programming language designed for extending applications. It is also frequently used as a general-purpose, stand-alone language. Lua is implemented as a small library of C functions, written in ANSI C, and compiles unmodified in all known platforms. The implementation goals are simplicity, efficiency, portability, and low embedding cost. The result is a fast language engine with small footprint, making it ideal in embedded systems too.
patterns   :
    - devel: [/usr/bin]
setup      : |
    %patch -p1 < $pkgfiles/0001-Enforce-usr-as-prefix-and-enable-shared-library.patch
build      : |
    %make linux
install    : |
    %make_install TO_LIB="liblua.so liblua.so.5.3 liblua.so.${version}"
    install -Dm00644 $pkgfiles/lua-5.3.pc $installdir/usr/lib/pkgconfig/lua-5.3.pc
